version: "3.8"

services:
#pra subir ambos os containers
  laravel:
    build: .
    container_name: laravel
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - faz_db

  faz_db:
    image: mysql:8
    container_name: faz_db
    restart: always
    environment:
      MYSQL_DATABASE: fazenda
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: